### ISSUE TITLE
Host of URIs w/ port but w/o protocol 

### ISSUE THREAD

**Issue by martinklepsch** [michaelklishin/urly#12]
```clojure
user=> (urly/host-of (urly/url-like "localhost:4711"))
nil
user=> (urly/host-of (urly/url-like "http://localhost:4711"))
"localhost"
user=> (-> "coogle.com:9000" urly/url-like urly/host-of)
nil
user=> (-> "http://coogle.com:9000" urly/url-like urly/host-of)
"coogle.com"
user=> (-> "coogle.com" urly/url-like urly/host-of)
"coogle.com"
```
I'm not sure if this is a bug or just not supported?

**Comment by michaelklishin** [comment]
We'd like to support this but this (and several other) issues mean we have to write a new URI parser. We don't have enough time for that, sadly. I believe there is a couple of alternative Clojure projects these days that have green field parsers.

**Comment by martinklepsch** [comment]
I see, sorry for the noise then.
