### ISSUE TITLE
Push latest version to Clojars

### ISSUE THREAD

**Issue by ricardojmendez** [michaelklishin/urly#14]
Hi,

It looks like the latest version on Clojars is Alpha 5 from two years ago, which depends on guava 11.0.1. Could you push the latest code as an alpha 6 for the updated Guava 18 dependencies?

**Comment by michaelklishin** [comment]
We can but Urly is not under active development.

**Comment by ricardojmendez** [comment]
Understood - I was going by the repo, not Clojars, and though it still was.

I'd still appreciate if you could release it, since it'll act as a band-aid while I replace it.  Perhaps a note on the README or the Clojurewerkz page might be in order.

Any alternate libraries you'd suggest?

Thanks!

**Comment by michaelklishin** [comment]
We'll try upgrading Guava; releasing is the easy part. I've also moved Urly to the deprecated projects section on clojurewerkz.org.

I can only recall [Exploding Fish](https://github.com/wtetzner/exploding-fish). There was a couple of more recent libraries doing something similar to Urly last year, too.

**Comment by ricardojmendez** [comment]
Thanks for the note.

Regarding the upgrade: looks like commit 813daa1 already upgraded it and all tests are passing.

**Comment by ricardojmendez** [comment]
One more thing... urly is currently a dependency for neocons. What brought me here in the first place was a [dependency conflict](http://numergent.com/2015-03/Chasing-after-NoSuchMethodError-com-google-common-io-ByteStreams-limit.html), which I expect updating urly will help me get rid of.

However, if urly is no longer being supported, will it be removed as a neocons dependency, or do you plan to keep it there?

Cheers.

**Comment by michaelklishin** [comment]
Neocons uses it very lightly. We can probably easily remove the dependency.

**Comment by ricardojmendez** [comment]
That'd be ideal. I'll file an issue to keep track of it.

**Comment by ricardojmendez** [comment]
Closing, will open a new issue to discuss future releases.
