### ISSUE TITLE
Documentation of ClojureWerkz deprecation

### ISSUE THREAD

**Issue by christianromney** [michaelklishin/urly#17]
Hi Michael,

I noticed that you moved urly to the deprecated projects section on ClojureWerkz but there's no notice here of that fact. Also, no real explanation of what that means is given. Is this project abandoned? Are there alternatives you could recommend? Any light you could shed on this would be much appreciated.

Cheers.

**Comment by michaelklishin** [comment]
It needs a completely new parser, and I don't have the time to develop one. Urly has made opinionated decisions that in some cases are more trouble than they are worth. There are also fairly good alternative these days, as opposed to 2011.
